export interface ArticleInput {
  title: string;
  description: string;
  body: string;
  tagList: string[];
}

let seq = 0;

/**
 * Article input factory: sensible, valid defaults with a unique title, plus any
 * overrides. Centralizes "what a test article looks like" so specs declare only
 * what they care about. (tagList defaults to [] — the API throws without it, Ch.13.)
 *
 * The title (and thus the slug) must be unique across PARALLEL WORKERS, so it mixes
 * a timestamp, a per-process counter, AND randomness — a timestamp+counter alone
 * collides when two workers generate one in the same millisecond.
 */
export function articleData(overrides: Partial<ArticleInput> = {}): ArticleInput {
  seq += 1;
  const stamp = `${Date.now()}-${seq}-${Math.floor(Math.random() * 1e9)}`;
  return {
    title: `Test Article ${stamp}`,
    description: "Generated by the article factory",
    body: "Article body for automated tests.",
    tagList: [],
    ...overrides,
  };
}
