export interface ArticleInput {
  title: string;
  description: string;
  body: string;
  tagList: string[];
}

let seq = 0;

/**
 * Article input factory: sensible, valid defaults with a unique title, plus any
 * overrides. Centralizes "what a test article looks like" so specs declare only
 * what they care about. (tagList defaults to [] — the API throws without it, Ch.13.)
 */
export function articleData(overrides: Partial<ArticleInput> = {}): ArticleInput {
  seq += 1;
  return {
    title: `Test Article ${Date.now()}-${seq}`,
    description: "Generated by the article factory",
    body: "Article body for automated tests.",
    tagList: [],
    ...overrides,
  };
}
