import { uniqueId } from "@utils/unique";

export interface ArticleInput {
  title: string;
  description: string;
  body: string;
  tagList: string[];
}

/**
 * Article input factory: sensible, valid defaults with a unique title, plus any
 * overrides. Centralizes "what a test article looks like" so specs declare only
 * what they care about. (tagList defaults to [] — the API throws without it, Ch.13.)
 *
 * The title (and thus the slug) must be unique across PARALLEL WORKERS — see
 * uniqueId for why a timestamp alone isn't enough.
 */
export function articleData(overrides: Partial<ArticleInput> = {}): ArticleInput {
  return {
    title: `Test Article ${uniqueId()}`,
    description: "Generated by the article factory",
    body: "Article body for automated tests.",
    tagList: [],
    ...overrides,
  };
}
